#baseURL = "https://cvarela-.42.fr/static"
title = "42"
theme = "m10c"
paginate = 8
canonifyURLs = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

[params]
  author = "Cesar M."
  description = "Student @42Urduliz"